### PR TITLE
Issues/5 reduce vertex count

### PR DESCRIPTION
**Pull request by mdutton3**
Addressing #5.
 
Developed and tested on Win7 with VS2013, DirectX and OpenGL. I have not tested for other platforms but see no reason that it shouldn't work there as well.

### CODE REVIEW

**Comment by russell-taylor** [comment]
I get a black window on Linux when I use this branch, but good images when I use the master branch.  I'll see if I can figure out what is going on tomorrow morning.  No error or warning messages.

**Comment by russell-taylor** [comment]
The initial commit that does index-based work inside the function and then converts back to vertices works, once I replace the "for each" with a standard for so it can compile on Linux.

**Comment by russell-taylor** [comment]
Clearing the screen to red before rendering the triangle mesh shows that the mesh is not showing up -- the window stays red.  Switching which face is front-facing doesn't change things.  It is drawing 38400 triangles in the glDrawArrays call.

**Comment by russell-taylor** [comment]
When I set these to what they seem like they should be (interleaved, with stride and offset), I get no triangles again.  When I set them to block layout, I get a whole screen full of triangles, but they are scrambled.

Giving up for now.

**Comment by mdutton3** [comment]
I'll try to get setup on Linux and look at this.

On Mon, Apr 25, 2016, 9:08 AM Russell Taylor <notifications@github.com>
wrote:

> When I set these to what they seem like they should be (interleaved, with
> stride and offset), I get no triangles again. When I set them to block
> layout, I get a whole screen full of triangles, but they are scrambled.
>
> Giving up for now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sensics/OSVR-RenderManager/pull/75#issuecomment-214310313>
>
-- 

--
Matt Dutton
404-406-1312 (cell)

**Pull request merged**
