### PR TITLE
Extended mode timing for d3d11

### PR DESCRIPTION
**Pull request by russell-taylor**
Implements (and then re-implements in a better way) render timing info in D3D11 extended mode.

### CODE REVIEW

**Comment by russell-taylor** [comment]
Implements the suggestion recommended in https://github.com/sensics/OSVR-RenderManager/issues/240

**Comment by rpavlik** [comment]
Does this end up providing good performance, then, without needing a separate thread to watch for VSYNC events? The separate thread approach was implied to be required by the GDC 2015 talk, but I'm happy if there's another way that works well enough.

**Comment by russell-taylor** [comment]
I've only tested with the hdk2.0 and a gtx 980m but it seemed to give reliable estimates except that it sometimes had an extra frame time for the next sync. Was able to work around that. Not all of the fields in the structure were reliable but I found a set that worked.

**Comment by russell-taylor** [comment]
This is going to be included in the upcoming just-in-timewarp request, which continues on this branch.  Closing this pull request because the new one will include it.

**Pull request closed without merging**
