### PR TITLE
Easy copying of RM dependencies

### PR DESCRIPTION
**Pull request by godbyk**
The primary purpose of this PR is to provide a method for RM clients to copy the RM libraries and its dependencies to the same installation directory as the client itself.

This is accomplished with the use of the `osvrrm_install_dependencies()` function in the `osvrRenderManagerConfig.cmake` file.

**Breaking change:** RenderManager consumers will need to change `osvrRenderManager` to `osvrRenderManager::osvrRenderManager` in their `CMakeLists.txt` files. For example:
```cmake
find_package(osvrRenderManager)
target_link_libraries(mytarget osvrRenderManager::osvrRenderManager)
```

https://github.com/OSVR/SteamVR-OSVR/pull/74 depends on this PR.

### CODE REVIEW

**Comment by russell-taylor** [comment]
When I configure Cmake, it puts a lot of messages about DLLs (see below for example) that are coming from the source tree, which is not the right place.  Maybe they should be from the build tree?

Adding F:/taylorr/Personal/Work/consulting/Sensics/OSVR/src/OSVR-RenderManager/bin/glew32.dll to OSVRRM_REQUIRED_LIBRARIES_DEBUG.

**Comment by russell-taylor** [comment]
The builds work, but when I try install, I get the following error. This error actually has two problems: (1) the obvious one, that it didn't work, and (2) the fact that I had hand-changed the location of the glew DLL to be a correct location in C:/usr/local/bin/x64 by hand after CMake auto-found the incorrect one at the location it copied from.

1>------ Build started: Project: INSTALL, Configuration: RelWithDebInfo x64 ------
1>  -- Install configuration: "RelWithDebInfo"
1>  -- Up-to-date: C:/Program Files/osvrRenderManager/bin/glew32.dll
1>  CMake Error at cmake_install.cmake:38 (file):
1>    file INSTALL cannot set permissions on "C:/Program
1>    Files/osvrRenderManager/bin/glew32.dll"
1>  
1>  
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "setlocal
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: "C:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=RelWithDebInfo -P cmake_install.cmake
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmErrorLevel
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: exit /b %1
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmDone
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code 1.
========== Build: 0 succeeded, 1 failed, 55 up-to-date, 0 skipped ==========

**Comment by russell-taylor** [comment]
The permission-setting problem on GLEW also happens in master, so is not the fault of this pull request.  This says to me that the pull request seems to be doing no harm, though it does seem to be confused about where to pull the DLLs from.

**Comment by godbyk** [comment]
@russell-taylor I'm definitely interested in it pulling from the wrong source.

What is the CMAKE_INSTALL_PREFIX set to?

The paths that it's adding to the config file are not the source locations of the libraries while building RenderManager, but rather their destination after installing RenderManager. They're purpose is to tell the consumer of RenderManager (e.g., SteamVR-OSVR) where it can find the libraries that should be copied along with the RenderManager libraries for it to run.

Something I failed to mention at the top (though I'll edit that post now) is that for consumers, this will break things slightly: They will need to change `osvrRenderManager` to `osvrRenderManager::osvrRenderManager` in their `CMakeLists.txt` files.

**Comment by russell-taylor** [comment]
CMAKE_INSTALL_PREFIX is C:/Program Files/osvrRenderManager.

**Comment by godbyk** [comment]
@russell-taylor Can you post the contents of the osvrRenderManagerConfig.cmake file that was installed?

**Comment by russell-taylor** [comment]
[osvrRenderManagerConfig.zip](https://github.com/sensics/OSVR-RenderManager/files/342202/osvrRenderManagerConfig.zip)

**Comment by rpavlik** [comment]
Destinations shouldn't be absolute at configure time but relative to the loaded location of the osvrRenderManagerConfig.cmake file, so the directory can be relocated.

**Comment by godbyk** [comment]
@rpavlik At one point I was trying to use paths relative to the config.cmake file for just the reason, but it didn't pan out due to some cmake restriction. I can't recall the details right off, though. I'll look into it again.

**Comment by godbyk** [comment]
@russell-taylor Can you run the latest version of this and paste the cmake output for me?

**Comment by russell-taylor** [comment]
Git reports version 00_06_43-182-geb9e7cd
Could NOT find OPENGLES2 (missing:  OPENGLES2_INCLUDE_DIR OPENGLES2_gl_LIBRARY) 
Git's description of the current revision indicates this is a prerelease of 07.34: version_07.33-310-ge75e92c

Configuring the VRPN suite version 07.34.0~prerelease-git-07.33-310-ge75e92c using the CMake-based build system

NOTE: You have VRPN_USE_LOCAL_HIDAPI enabled, but VRPN_USE_HID disabled: HIDAPI will only be built if you enable HID support for VRPN
 - D3D11 support: enabled (found WIN32)
 - NVIDIA direct D3D11 support: enabled (found NVAPI and NVIDIA NDA submodule)
 - AMD direct D3D11 support: enabled (found LIQUIDVR and AMD NDA submodule)
 - OpenGL support: enabled
 - D3D11+OpenGL support: enabled (found NVAPI or LIQUIDVR, OpenGL, GLEW, and SDL2)
Absolute path to installed libraries: F:/taylorr/Personal/Work/consulting/Sensics/OSVR/src/OSVR-RenderManager/bin
Absolute path to CMake config: F:/taylorr/Personal/Work/consulting/Sensics/OSVR/src/OSVR-RenderManager/lib/cmake/osvrRenderManager
Relative path to installed libraries: ../../../bin
Adding ../../../bin/glew32.dll to OSVRRM_REQUIRED_LIBRARIES_DEBUG.
Adding ../../../bin/glew32.dll to OSVRRM_REQUIRED_LIBRARIES_RELEASE.
Adding ../../../bin/glew32.dll to OSVRRM_REQUIRED_LIBRARIES_RELWITHDEBINFO.
Adding ../../../bin/glew32.dll to OSVRRM_REQUIRED_LIBRARIES_MINSIZEREL.
Adding ../../../bin/SDL2.dll to OSVRRM_REQUIRED_LIBRARIES_DEBUG.
Adding ../../../bin/SDL2.dll to OSVRRM_REQUIRED_LIBRARIES_RELEASE.
Adding ../../../bin/SDL2.dll to OSVRRM_REQUIRED_LIBRARIES_RELWITHDEBINFO.
Adding ../../../bin/SDL2.dll to OSVRRM_REQUIRED_LIBRARIES_MINSIZEREL.
Adding ../../../bin/osvrClientKitd.dll to OSVRRM_REQUIRED_LIBRARIES_DEBUG.
Adding ../../../bin/osvrClientKit.dll to OSVRRM_REQUIRED_LIBRARIES_RELEASE.
Adding ../../../bin/osvrClientKit.dll to OSVRRM_REQUIRED_LIBRARIES_RELWITHDEBINFO.
Adding ../../../bin/osvrClientKit.dll to OSVRRM_REQUIRED_LIBRARIES_MINSIZEREL.
Adding ../../../bin/osvrClientd.dll to OSVRRM_REQUIRED_LIBRARIES_DEBUG.
Adding ../../../bin/osvrClient.dll to OSVRRM_REQUIRED_LIBRARIES_RELEASE.
Adding ../../../bin/osvrClient.dll to OSVRRM_REQUIRED_LIBRARIES_RELWITHDEBINFO.
Adding ../../../bin/osvrClient.dll to OSVRRM_REQUIRED_LIBRARIES_MINSIZEREL.
Adding ../../../bin/osvrCommond.dll to OSVRRM_REQUIRED_LIBRARIES_DEBUG.
Adding ../../../bin/osvrCommon.dll to OSVRRM_REQUIRED_LIBRARIES_RELEASE.
Adding ../../../bin/osvrCommon.dll to OSVRRM_REQUIRED_LIBRARIES_RELWITHDEBINFO.
Adding ../../../bin/osvrCommon.dll to OSVRRM_REQUIRED_LIBRARIES_MINSIZEREL.
Adding ../../../bin/osvrUtild.dll to OSVRRM_REQUIRED_LIBRARIES_DEBUG.
Adding ../../../bin/osvrUtil.dll to OSVRRM_REQUIRED_LIBRARIES_RELEASE.
Adding ../../../bin/osvrUtil.dll to OSVRRM_REQUIRED_LIBRARIES_RELWITHDEBINFO.
Adding ../../../bin/osvrUtil.dll to OSVRRM_REQUIRED_LIBRARIES_MINSIZEREL.
Configuring done

**Comment by godbyk** [comment]
@russell-taylor Those values look sensible to me. Do the libraries end up installed in `F:/taylorr/Personal/Work/consulting/Sensics/OSVR/src/OSVR-RenderManager/bin` when run build the `INSTALL` target or run `make install`?

**Comment by russell-taylor** [comment]
They do now, when I remember to install as admin.  Let me know when you want me to merge.

**Comment by godbyk** [comment]
@russell-taylor It sounds like we're good to go then. Thanks!

**Pull request merged**
