### PR TITLE
RenderManager: Replace None by Zero.

### PR DESCRIPTION
**Pull request by Armada651**
None is a reserved keyword in X11.

### CODE REVIEW

**Comment by godbyk** [comment]
@Armada651 Do you have a citation for this? Is None defined as a macro somewhere in X11? Thanks!

**Comment by Armada651** [comment]
Here you go, you can find it on this page:
https://refspecs.linuxfoundation.org/LSB_1.3.0/gLSB/gLSB/libx11-ddefs.html

**Comment by godbyk** [comment]
Thanks!

Unfortunately, it's not possible for us to defend against every possible macro definition in the world.

If you're including `X11/X.h` and also `osvr/RenderKit/RenderManager.h` in your code, you can work around the X11 `None` definition with the following code:

```c++
#include <X11/X.h> // defines None = 0L

// Temporarily undefine the None macro so it doesn't conflict with
// osvr::RenderKit::ConstructionParameters::Display_Rotation::None
#pragma push_macro("None")
#undef None

#include <osvr/RenderKit/RenderManager.h>

// Restore X11's definition of None macro
#pragma push_macro("None")

// Anywhere after this point, None == 0L again.
```

The `#pragma push_macro("None")` works in GCC, Clang, and MSVC.

**Comment by Armada651** [comment]
I understand you cannot defend against every macro definition, but I think it's useful to take into account macros in major headers for the operating systems you support. This is a small change that will save Linux developers a lot of headaches.

**Comment by Armada651** [comment]
Also the problem is that I need to include RenderManager.h in the header of my class, which causes it to be included everywhere and ultimately it's going to get included somewhere together with X.h.

The reason I'm including RenderManager.h in my class header is because I can't forward declare the typedef structs like RenderInfo, because they're anonymous. If we don't want to defend against major operating system headers, then the only proper solution is to give all your structs full names so we can forward declare them.

**Comment by russell-taylor** [comment]
This is the sort of thing I thought that namespaces were supposed to fix.  It looks like the pull request does all the work needed to avoid the problem and it doesn't seem to cause any other problems, so I'm going to say "thank you for submitting a fix" and merge it.  It makes me wonder if we should make an issue to find a better way to hide all of this that doesn't make clients forward-declare things in their code.

**Pull request merged**
